# Generated by Django 2.2 on 2019-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pearson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
